In [ ]:
import numpy as m
dt=m.dtype([('age',m.int8)])   ## making custom data type age of integer type with 8 bit
#  https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html
a=m.array([(10),(20),(30),(40)],dtype=dt)   #creating array of elements and 
# applying above data type to the elements of the array
print(a)            #  printing array
print(a['age'])     #printing only elements of tye array

[(10,) (20,) (30,) (40,)]
[10 20 30 40]


In [ ]:
import numpy as mp   #importing numpy and assigning it to mp
dt=mp.dtype(mp.int32)    ## making custom data type age of integer type with 32 bit
#  https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html
print(dt)

int32


In [2]:
import numpy as m       #importing numpy and assigning it to m
student=m.dtype([('name','S20'),('age','i1'),('marks','f4')])  ## making custom data type student
# for custom array type  
#name here S means string 20 means bit size,      i means integer ,   f means float
print(student)
a=m.array([('abc',19,25.5),('ppp',56,6.5),('jjjj',85,56.6)])  #cgreating an array
print(a)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]
[['abc' '19' '25.5']
 ['ppp' '56' '6.5']
 ['jjjj' '85' '56.6']]


In [5]:
import numpy as mps         #importing numpy and assigning it to mp
x=mps.array([[1,2],[3,4],[5,6]])     # creating an array of two element block of matrix
y=x[[0,1,2],[0,1,0]]            # taking out elemet from array x fom the comination of index (i,i)

print(x)    
print(y)

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
