In [1]:
import pandas as pd  #importing pandas
import numpy as np    #importing numpy
df_new= pd.read_csv('/home/manpreet/mps/cc/aclImdb_v1/aclImdb/movie_reviews.csv')   #reading csv
df_new.head()    #print some value from top of df_new
print(df_new)


 



                                                  review  sentiment
0      Richard Brooks' The Last Hunt was a film star ...          1
1      Pat Conroy's autobiographical book "The Water ...          1
2      The Five Deadly Venoms is easily the most memo...          1
3      An interesting concept turned into carnage...<...          0
4      Its not Braveheart( thankfully),but it is fine...          1
5      I saw this movie a few years back on the BBC i...          0
6      This movie was so bad I couldn't sit through i...          0
7      Maybe the greatest film ever about jazz.<br />...          1
8      One of the last surviving horror screen greats...          0
9      New York attorney plots to rid himself of his ...          0
10     As a French, i found it very pleasant to be ab...          1
11     I can't believe I even tried to watch this fil...          0
12     I saw this movie once in or close to its relea...          1
13     I've waited a long time to see DR TARR'S 

In [39]:

df_new.sentiment.value_counts()  #this counts the occurance of allsentiments and print the correspondence value

1    25000
0    25000
Name: sentiment, dtype: int64

In [40]:

from sklearn.utils import shuffle
print(df_new.head())
df_new = shuffle(df_new)     #shuffling the values in df_new
print(df_new.head())


                                              review  sentiment
0  Richard Brooks' The Last Hunt was a film star ...          1
1  Pat Conroy's autobiographical book "The Water ...          1
2  The Five Deadly Venoms is easily the most memo...          1
3  An interesting concept turned into carnage...<...          0
4  Its not Braveheart( thankfully),but it is fine...          1
                                                  review  sentiment
11235  "The Aristocats" is classic Disney at it's bes...          1
7877   This is one of those movies that they did too ...          1
41364  I only saw this movie once, and that was enoug...          0
40445  As I said, sometimes low budget is good. You g...          0
25345  Considering all the teen films like "the Break...          1


In [41]:
import re    ##importing regular expression
def preprocessor(text):   #function to remove extra thing from the string for ex emoticons
    
    #we are using regular expression to determine emoticons and other extra things
   text = re.sub('<[^>]*>','',text)     
   emoticons = re.findall('[:;=](?:-)', text)
   text = (re.sub('[\W]+',' ',text.lower())+ ' '.join(emoticons).replace('-',''))
   
   return text


In [42]:
preprocessor("</a>This is# a ;test ::-)!</a>")   #example what above function is doing

'this is a test :'

In [43]:
df_new['review'] = df_new['review'].apply(preprocessor)   #applying above defined function to all the reviews and
#then replacing those reviews
df_new.head()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>review</th>
      <th>sentiment</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>11235</th>
      <td>the aristocats is classic disney at it s best...</td>
      <td>1</td>
    </tr>
    <tr>
      <th>7877</th>
      <td>this is one of those movies that they did too ...</td>
      <td>1</td>
    </tr>
    <tr>
      <th>41364</th>
      <td>i only saw this movie once and that was enough...</td>
      <td>0</td>
    </tr>
    <tr>
      <th>40445</th>
      <td>as i said sometimes low budget is good you get...</td>
      <td>0</td>
    </tr>
    <tr>
      <th>25345</th>
      <td>considering all the teen films like the breakf...</td>
      <td>1</td>
    </tr>
  </tbody>
</table>
</div>

In [44]:
df_new.index  =range(50000)
df_new.head()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>review</th>
      <th>sentiment</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>the aristocats is classic disney at it s best...</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1</th>
      <td>this is one of those movies that they did too ...</td>
      <td>1</td>
    </tr>
    <tr>
      <th>2</th>
      <td>i only saw this movie once and that was enough...</td>
      <td>0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>as i said sometimes low budget is good you get...</td>
      <td>0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>considering all the teen films like the breakf...</td>
      <td>1</td>
    </tr>
  </tbody>
</table>
</div>

In [45]:
X_train = df_new.loc[:2500,'review'].values
y_train = df_new.loc[:2500,'sentiment'].values
X_test = df_new.loc[2500:,'review'].values
y_test = df_new.loc[2500:,'sentiment'].values

In [46]:
print(np.bincount(y_test))





# bincount creates the list of counts of index that occur in the list

#for ex a=[1,2,1,3,4,5,5,5]
#index are 0,1,2,3,4,5,6,7 respectively for 1,2,1,3,4,5,5,5

#bincount will count the occurrence of index in self 
# ex below
print("\n\nEXample result\n")
a=np.array([1,2,1,3,4,5,5,5])
print(np.bincount(a))

#occurrence of INDEX is NO.OF TIME in array a
#occurrence of 0 is 0 in array a
#occurrence of 1 is 2 in array a
#occurrence of 2 is 1 in array a
#occurrence of 2 is 2 in array a






[23773 23727]


EXample result

[0 2 1 1 1 3]


In [47]:
print(np.unique(y_test))

#print all the unique values in array means no repeatation

#example
print("\n\nEXample result\n")
a=np.array([1,2,1,3,4,5,5,5])
print(np.unique(a))



[0 1]


EXample result

[1 2 3 4 5]


In [48]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression   #for predection
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
from sklearn.model_selection import GridSearchCV #hyper-path

In [49]:
tfidf = TfidfVectorizer(stop_words='english')    #initialising TfidfVectorizer   

#this creates the matrix of tfids for each word in the input file

#stop_words='english is used to ignore common english word like 'the' 'a' which does not have meaning


#https://stackoverflow.com/questions/34449127/sklearn-tfidf-transformer-how-to-get-tf-idf-values-of-given-words-in-documen

#example

testtfidf=TfidfVectorizer(stop_words='english')

corpus = ["hotel food","hotel food service"]
testtfidf.fit_transform(corpus)
print(testtfidf.vocabulary_)

{'hotel': 1, 'food': 0, 'service': 2}


In [69]:

param_grid = {'clf__C':[1.0,10.0,100.0]}
X_train.ndim   #print the Number of array dimensions.

#here dimension means real world dimensions 1d 2d 3d or nd

#example is given below


1

In [70]:

a1 = np.array(111)
b1 = np.array([1,2])
c1 = np.array([[1,2], [4,5]])
d1 = np.array([[1,2,3,], [4,5,]])
e1=np.array([[1,2,3],[4,5,6],[7,8,9]])
f1=np.array([[[0, 0, 0], [0, 0, 0], [0, 0, 0]],
 [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
 [[0, 0, 0], [0, 0, 0], [0, 0, 0]]])   #this is a 3d array
print(a1.ndim, b1.ndim, c1.ndim, d1.ndim, e1.ndim,f1.ndim)


0 1 2 1 2 3


In [71]:
Ir_tfidf = Pipeline([('vect',tfidf),('clf',LogisticRegression())])


#applying multiple transform sequentially and then estimater


#http://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html

#https://stackoverflow.com/questions/33091376/python-what-is-exactly-sklearn-pipeline-pipeline






gs_Ir_tfidf = GridSearchCV(Ir_tfidf,param_grid,scoring='accuracy')

#Exhaustive search over specified parameter values for an estimator.

#http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html

In [72]:
gs_Ir_tfidf.fit(X_train,y_train)




GridSearchCV(cv=None, error_score='raise',
       estimator=Pipeline(memory=None,
     steps=[('vect', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
  ...ty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False))]),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'clf__C': [1.0, 10.0, 100.0]}, pre_dispatch='2*n_jobs',
       refit=True, return_train_score='warn', scoring='accuracy',
       verbose=0)

GridSearchCV(cv=None, error_score='raise',
       estimator=Pipeline(memory=None,
     steps=[('vect', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
  ...ty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False))]),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'clf__C': [1.0, 10.0, 1000.0]}, pre_dispatch='2*n_jobs',
       refit=True, return_train_score='warn', scoring='accuracy',
       verbose=0)

In [ ]:
print('Best parameter set: %s ' % gs_Ir_tfidf.best_params_)
#best_params_
#Parameter setting that gave the best results on the hold out data.



print('CV Accuracy: %.3f' % gs_Ir_tfidf.best_score_)


#best_score_
#Mean cross-validated score of the best_estimator


Pipeline(memory=None,
     steps=[('vect', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
  ...ty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False))])


In [78]:
print(gs_Ir_tfidf.best_estimator_)

#Estimator that was chosen by the search, 
# i.e. estimator which gave highest score (or smallest loss if specified) on the left out data.


Pipeline(memory=None,
     steps=[('vect', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
  ...ty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False))])


In [79]:
clf.score(X_test,y_test)

0.8479368421052632

In [80]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
nb = Pipeline([('vect', tfidf),('clf', MultinomialNB())])

#The multinomial Naive Bayes classifier is suitable for classification with discrete features 
# (e.g., word counts for text classification). The multinomial distribution normally requires integer
#  feature counts. However, in practice, fractional counts such as tf-idf may also work.


[[3 4 3 0 4]
 [1 4 0 4 0]
 [0 3 1 4 1]
 [2 3 1 1 2]
 [1 2 0 0 0]
 [4 0 3 3 2]] 

[1 2 3 4 5 6] 

[[0 3 1 4 1]]
[3]


In [102]:
##example of multinomial Naive Bayes
Xx= np.random.randint(5, size=(6, 5))
print(Xx,"\n")

yy= np.array([1, 2, 3, 4, 5, 6])
print(yy,"\n")
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(Xx, yy)
MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)
print(Xx[2:3])
print(clf.predict(Xx[2:3]))

[[3 4 3 0 4]
 [1 4 0 4 0]
 [0 3 1 4 1]
 [2 3 1 1 2]
 [1 2 0 0 0]
 [4 0 3 3 2]] 

[1 2 3 4 5 6] 

[[0 3 1 4 1]]
[3]


In [103]:
nb.fit(X_train,y_train)

Pipeline(memory=None,
     steps=[('vect', TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
  ...rue,
        vocabulary=None)), ('clf', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])

In [104]:
nb.score(X_train,y_train)

0.9768092762894842

In [106]:
nb.score(X_test,y_test)


(2501, 28276)

In [107]:

cv = TfidfVectorizer(stop_words='english')

(2501, 28276)

In [109]:

new_data = cv.fit_transform(X_train)
new_test = cv.transform(X_test)
new_data.shape

(2501, 28276)

In [110]:


nb = MultinomialNB()
nb.fit(new_data,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [111]:
nb.score(new_test,y_test)

0.8403578947368421

In [112]:
nb.score(new_data,y_train)

0.9768092762894842